import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 2,
  workers: 1,
  reporter: process.env.CI ? "html" : "list",
  timeout: 60_000,
  use: {
    trace: "on-first-retry",
  },
  globalSetup: "./global-setup",
  globalTeardown: "./global-teardown",
  // Membership gate only — new specs must be added here to run at all.
  // NOTE: testMatch does NOT control order; specs execute alphabetically.
  testMatch: [
    "routing.spec.ts",
    "pe-reader.spec.ts",
    "drag-drop.spec.ts",
    "keyboard-shortcuts.spec.ts",
    "windows-menu.spec.ts",
    "patches.spec.ts",
    "image-patch.spec.ts",
    "symbol-persist.spec.ts",
    "bookmarks.spec.ts",
    "disassembly.spec.ts",
    "input-history.spec.ts",
    "pc-follow.spec.ts",
    "emulation-highlight.spec.ts",
    "navigation-history.spec.ts",
    "symbol-status.spec.ts",
    "symbol-breakpoints.spec.ts",
    "types.spec.ts",
    "registers.spec.ts",
    "session-lifecycle.spec.ts",
    "restart-and-unload.spec.ts",
    "stepping.spec.ts",
    "source-view.spec.ts",
    "attach-detach.spec.ts",
    "non-invasive.spec.ts",
    "strings-view.spec.ts",
    "memory-regions.spec.ts",
    "code-explorer.spec.ts",
    "watchpoint-trace.spec.ts",
  ],
});
