name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch: [ARM64, X64-native]
    runs-on:
      - self-hosted
      - Windows
      - ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build Tauri app
      run: npm run tauri build
    
    - name: Rename executable for architecture
      run: |
        if ("${{ matrix.arch }}" -eq "X64-native") {
          Rename-Item -Path "src-tauri/target/release/joybug-tauri.exe" -NewName "joybug-tauri-x64.exe"
        } elseif ("${{ matrix.arch }}" -eq "ARM64") {
          Rename-Item -Path "src-tauri/target/release/joybug-tauri.exe" -NewName "joybug-tauri-aarch64.exe"
        }
      shell: powershell
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-app-${{ matrix.arch }}
        path: src-tauri/target/release/joybug-tauri-*.exe